#Variables nécessaires aux Makefiles
CC = gcc
DEBUG = yes
EXEC = faroShell
C99FLAG = -std=c99

ifeq ($(DEBUG),yes)
        CFLAGS = -fPIC -pedantic -Wall -Wextra
else
        CFLAGS = -fPIC -pedantic
endif

src = src
interpreter = interpreter
cmd = cmd
bin = bin
obj = obj
static = static
shared = shared
objCmd = obj/cmd
binCmd = bin/cmd
objects = lecture.o main.o parse.o liste.o stack.o
commands = echo.o
OBJS = $(patsubst %,$(obj)/%,$(objects))
